### ISSUE TITLE
rack-affiliate for rails5api-only

### ISSUE THREAD

**Issue by megetron** [alexlevin/rack-affiliates#15]
The design of the rack-affiliates based on sessions/cookies.

a project is needed to be converted to API mode with angular. 

is it possible to make the project API support?

**Comment by timrwilliams** [comment]
This gem is being maintained and accepts pull requests but we're not actively developing any major features on it. You're welcome to fork the project and modify it to your needs or submit a pull request if your changes are backwards compatible. 

Off the top of my head you'd need your angular code to capture the initial referral code and then keep hold of it until you call your user registration code on the rails API at which point you can associate this with the new user in the same manner that we do currently. Good luck.
